### ISSUE TITLE
PymRMR crashes on number conversion

### ISSUE THREAD

**Issue by litozz** [fbrundu/pymrmr#113]
* PymRMR version: 0.1.8
* Python version: 3.5
* Operating System: Ubuntu 16.04 LTS

### Description

PymRMR crashes in conversion when I want to execute with a correct dataset.

### What I Did

I read a dataset (it haven't NaN's or missing values), then I put the target on columns position 0. The dataset (included target) now have 10 variables. If I want to remove 1 variable, i.e. I want 8 predictors, I get the following error:

```
Traceback (most recent call last):
  File "/home/carlos/Escritorio/Trabajo/PredXmax/src/preprocess_data.py", line 62, in <module>
    pymrmr.mRMR(qgsjet_train_full_ds,'MIQ',8)
  File "pymrmr/pymrmr.pyx", line 19, in pymrmr.mRMR (pymrmr/pymrmr.cpp:1666)
  File "stringsource", line 53, in vector.from_py.__pyx_convert_vector_from_py_std_3a__3a_vector_3c_int_3e___ (pymrmr/pymrmr.cpp:4546)
  File "stringsource", line 52, in vector.from_py.__pyx_convert_vector_from_py_int (pymrmr/pymrmr.cpp:4428)
OverflowError: value too large to convert to int
```

**Comment by fbrundu** [comment]
Hey @litozz ,
I am sorry you had this problem. Can you send me a minimal dataset to reproduce and debug your error?

Thanks,
Francesco

**Comment by yangyunshuai** [comment]
> * PymRMR version: 0.1.8
> * Python version: 3.5
> * Operating System: Ubuntu 16.04 LTS
> 
> ### Description
> PymRMR crashes in conversion when I want to execute with a correct dataset.
> 
> ### What I Did
> I read a dataset (it haven't NaN's or missing values), then I put the target on columns position 0. The dataset (included target) now have 10 variables. If I want to remove 1 variable, i.e. I want 8 predictors, I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/.../preprocess_data.py", line 62, in <module>
>     pymrmr.mRMR(full_ds,'MIQ',8)
>   File "pymrmr/pymrmr.pyx", line 19, in pymrmr.mRMR (pymrmr/pymrmr.cpp:1666)
>   File "stringsource", line 53, in vector.from_py.__pyx_convert_vector_from_py_std_3a__3a_vector_3c_int_3e___ (pymrmr/pymrmr.cpp:4546)
>   File "stringsource", line 52, in vector.from_py.__pyx_convert_vector_from_py_int (pymrmr/pymrmr.cpp:4428)
> OverflowError: value too large to convert to int
> ```

Hey, I have this problem, too. Do you have a solution?

**Comment by yangyunshuai** [comment]
@litozz Hey, I have this problem, too. Do you have a solution?

**Comment by Totothejuggler** [comment]
I'm having the same issue, was there ever a solution found for this?
